/**
 * explain.js — contextual "Explain this" content for the dashboard (Phase 1: Educate)
 *
 * Turns each dashboard number into a plain-English explanation grounded in the user's
 * REAL data, plus the relevant glossary terms. All text is generated by deterministic
 * templates here — the LLM is never in the browser hot path (see ROADMAP.md). Claude-
 * authored analysis arrives later (Phase 2) via Drive, not from this file.
 *
 * Public API:
 *   Explain.short(key)        → short string for the hover tooltip (no live data needed)
 *   Explain.metric(key, ctx)  → { title, short, context, glossary } for the click modal
 *   Explain.positionShort     → short string for a position's hover tooltip
 *   Explain.position(pos)     → { title, short, context, glossary } for a position
 *
 * ctx for metric() = { account, clock, positions, openOrders, dailyPnl }
 */

const Explain = (() => {
  const findTerm     = (t) => (CONFIG.glossary || []).find(g => g.term.toLowerCase() === t.toLowerCase());
  const glossaryList = (terms) => terms.map(findTerm).filter(Boolean);

  const POSITION_SHORT = 'Your stake in this stock and how much it has gained or lost so far.';

  const METRICS = {
    portfolioValue: {
      title: 'Portfolio Value',
      short: 'Everything your account is worth right now — cash plus the market value of all your positions.',
      terms: ['P&L', 'Buying Power'],
      context: ({ account, dailyPnl }) => {
        if (!account) return 'This is everything your account is worth: cash plus the market value of every position you hold.';
        const open = parseFloat(account.last_equity || 0);
        const dir  = dailyPnl >= 0 ? 'up' : 'down';
        return `This is everything your account is worth right now — cash plus the market value of every position you hold. ` +
               `It opened today at ${Utils.formatCurrency(open)}, so you're ${dir} ${Utils.formatPnL(dailyPnl)} on the day.`;
      },
    },

    dailyPnl: {
      title: "Today's Change",
      short: 'How much your portfolio value has moved since the market last closed.',
      terms: ['P&L'],
      context: ({ account, dailyPnl }) => {
        if (!account) return "How much your portfolio's value has changed since the previous close.";
        const prev = parseFloat(account.last_equity || 0);
        const now  = parseFloat(account.equity || 0);
        const pct  = prev ? (now - prev) / prev : 0;
        const dir  = dailyPnl >= 0 ? 'gained' : 'lost';
        return `Since the previous close your portfolio has ${dir} ${Utils.formatPnL(dailyPnl)} (${Utils.formatPercent(pct)}), ` +
               `moving from ${Utils.formatCurrency(prev)} to ${Utils.formatCurrency(now)}. ` +
               `This is unrealized — it keeps changing until you sell.`;
      },
    },

    buyingPower: {
      title: 'Buying Power',
      short: 'The money available to place new trades right now.',
      terms: ['Buying Power', 'Paper Trading'],
      context: ({ account }) => {
        const bp = account ? Utils.formatCurrency(parseFloat(account.buying_power || 0)) : 'your buying power';
        const paperNote = Alpaca.isPaper()
          ? ' This is a paper account, so it started with $100,000 of simulated cash — no real money is at risk.'
          : '';
        return `${bp} is what you can spend on new trades right now. It can be larger than your cash if margin is enabled.${paperNote}`;
      },
    },

    positions: {
      title: 'Positions',
      short: 'The number of different stocks you currently own.',
      terms: ['Position'],
      context: ({ positions }) => {
        const n = (positions || []).length;
        if (n === 0) return `You don't hold any positions yet. A "position" is a stock you own — once you buy one through the Alpaca MCP server, it shows up here.`;
        return `You currently hold ${n} ${n === 1 ? 'position' : 'positions'} — distinct stocks you own. ` +
               `Each is a "long" position: you profit if its price rises and lose if it falls.`;
      },
    },

    openOrders: {
      title: 'Open Orders',
      short: "Orders you've placed that haven't filled yet.",
      terms: ['Limit Order', 'Market Order'],
      context: ({ openOrders }) => {
        const n = (openOrders || []).length;
        if (n === 0) return `You have no open orders. An order shows up here when it's been placed but hasn't executed yet — for example, a limit order waiting for its target price.`;
        return `You have ${n} open ${n === 1 ? 'order' : 'orders'} — ${n === 1 ? 'it has' : 'they have'} been placed but ${n === 1 ? "hasn't" : "haven't"} filled yet. ` +
               `${n === 1 ? 'It sits' : 'They sit'} here until ${n === 1 ? 'it executes' : 'they execute'}, you cancel, or ${n === 1 ? 'it expires' : 'they expire'}.`;
      },
    },

    market: {
      title: 'Market Status',
      short: 'Whether the US stock market is currently open for regular trading.',
      terms: ['Market Hours', 'Pre-Market', 'After-Hours'],
      context: ({ clock }) => {
        const base = 'US markets trade 9:30am–4:00pm ET, Monday through Friday, excluding holidays.';
        if (!clock) return base;
        if (clock.is_open) {
          const close = clock.next_close ? ` Today's session closes at ${Utils.formatDateTime(clock.next_close)}.` : '';
          return `The market is open for regular trading. ${base}${close}`;
        }
        const open = clock.next_open ? ` The next session opens ${Utils.formatDateTime(clock.next_open)}.` : '';
        return `The market is closed right now. ${base}${open}`;
      },
    },
  };

  return {
    short(key) { return METRICS[key]?.short || ''; },

    metric(key, ctx) {
      const m = METRICS[key];
      if (!m) return null;
      return { title: m.title, short: m.short, context: m.context(ctx || {}), glossary: glossaryList(m.terms) };
    },

    positionShort: POSITION_SHORT,

    position(pos) {
      const qty    = parseFloat(pos.qty);
      const entry  = parseFloat(pos.avg_entry_price);
      const cur    = parseFloat(pos.current_price);
      const value  = parseFloat(pos.market_value);
      const pl     = parseFloat(pos.unrealized_pl);
      const plpc   = parseFloat(pos.unrealized_plpc);
      const dir    = pl >= 0 ? 'up' : 'down';
      const shares = `${Utils.formatShares(qty)} ${qty === 1 ? 'share' : 'shares'}`;
      return {
        title: `${pos.symbol} — your position`,
        short: POSITION_SHORT,
        context: `You own ${shares} of ${pos.symbol}, bought at an average price of ${Utils.formatCurrency(entry)}. ` +
                 `At the current price of ${Utils.formatCurrency(cur)} the position is worth ${Utils.formatCurrency(value)}, ` +
                 `${dir} ${Utils.formatPnL(pl)} (${Utils.formatPercent(plpc)}) since you bought. ` +
                 `That profit or loss is "unrealized" — it keeps changing with the price until you sell.`,
        glossary: glossaryList(['Position', 'P&L']),
      };
    },
  };
})();
